name: SolItems
version: '${version}'
main: dev.jsinco.solitems.SolItems
api-version: '1.20'
softdepend: [PlaceHolderAPI]
permissions:
  solitems.command.give:
    description: Gives a player a SolItem
    default: op
commands:
  solitems:
    description: SolItems command
